export const routes = {
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  admin: "/admin",
  adminLogs: "/admin/logs",
  expenses: "/expenses",
  expensesFijos: "/expenses/fijos",
  expensesIngresos: "/expenses/ingresos",
  expensesCuentas: "/expenses/cuentas",
  expensesVacaciones: "/expenses/vacaciones",
  expensesResumen: "/expenses/resumen",
  notes: "/notes",
  assistant: "/assistant",
  athleteDashboard: "/athlete-dashboard",
  athleteDashboardAthletes: "/athlete-dashboard/athletes",
  athleteTracker: "/athlete-tracker",
  clientSettings: "/client-settings",
  miembros: "/miembros",
} as const;
